package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"channel/graph/model"
)

var channels = []model.Channel{
	{
		ContentID: "content1",
		Text:      "Channel 1",
		Done:      false,
		User: &model.User{
			ContentID: "content1",
			Name:      "User 1",
		},
	},
	{
		ContentID: "content2",
		Text:      "Channel 2",
		Done:      false,
		User: &model.User{
			ContentID: "content2",
			Name:      "User 2",
		},
	},
	{
		ContentID: "content5",
		Text:      "Channel 5",
		Done:      true,
		User: &model.User{
			ContentID: "content5",
			Name:      "User 5",
		},
	},
	{
		ContentID: "content3",
		Text:      "Channel 3",
		Done:      true,
		User: &model.User{
			ContentID: "content3",
			Name:      "User 3",
		},
	},
	{
		ContentID: "content6",
		Text:      "Channel 6",
		Done:      true,
		User: &model.User{
			ContentID: "content6",
			Name:      "User 6",
		},
	}, {
		ContentID: "content4",
		Text:      "Channel 4",
		Done:      true,
		User: &model.User{
			ContentID: "content4",
			Name:      "User 4",
		},
	},
}
