package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"channel/graph/model"
	"context"
	"fmt"
)

// GetChannel is the resolver for the GetChannel field.
func (r *queryResolver) GetChannel(ctx context.Context, contentIds []string) ([]*model.Channel, error) {
	ret := []*model.Channel{}

	for _, contentID := range contentIds {
		fmt.Println(contentID)
		for _, channel := range channels {
			if channel.ContentID == contentID {
				ret = append(ret, &channel)
			}
		}
	}
	return ret, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
