// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Channel struct {
	ContentID string `json:"content_id"`
	Text      string `json:"text"`
	Done      bool   `json:"done"`
	User      *User  `json:"user"`
}

func (Channel) IsEntity() {}

type Query struct {
}

type User struct {
	ContentID string `json:"content_id"`
	Name      string `json:"name"`
}
